### ISSUE TITLE
About scatterformer.yaml ！！！

### ISSUE THREAD

**Issue by luoxiaoliaolan** [skyhehe123/ScatterFormer#3]
Thank you very much for your excellent work. I believe that the transformer structure definitely has greater potential for sparse 3D point cloud perception tasks. Currently, the existing transformer structures for 3D point cloud perception tasks indeed face issues of high resource consumption and slow processing efficiency. Moreover, in order to adapt to limited computational resources (GPUs), when I used the transformer structure for 3D object detection in point clouds, I found that the receptive field for feature extraction was relatively small. This resulted in poor detection performance for large objects like trucks with oversized dimensions. I would like to understand what characteristics ScatterFormer possesses compared to the DSVT method. Additionally, I noticed that you have added the ScatterFormer class in backbone3d, but there is no relevant model configuration file provided to use this implementation. I saw in your uploaded .vscode folder a configuration named "cfgs/waymo_models/scatterformer.yaml", but I couldn't find it. I hope you can upload the relevant model and data configurations for ScatterFormer on various datasets. I would like to use ScatterFormer to validate my own dataset and look forward to staying in touch with you!

**Comment by qzhang-nuro** [comment]
agreed. it looks like `cfgs/waymo_models/scatterformer.yaml` is somehow missing from the main branch. 
meanwhile, the configs from the README's `Main Results` section seem to be pointing to configs that are not present.
could they be added to the main branch?
thanks!
